#!/usr/bin/env python3
"""Attest the canonical dogfood pair from its existing build receipts.

Read-only: never signs, installs, launches, registers an extension or changes
permissions. A sealed receipt is not a live-runtime readiness receipt.
"""

from __future__ import annotations

import argparse
import ctypes
from datetime import datetime, timezone
import stat
import hashlib
import io
import json
import os
from pathlib import Path
import plistlib
import pwd
import re
import subprocess
import tarfile
import xml.etree.ElementTree as ET


class PairVerificationError(ValueError):
    pass


def fingerprint(value):
    return hashlib.sha256(json.dumps(value, sort_keys=True,
        separators=(",", ":"), ensure_ascii=False).encode()).hexdigest()


def file_hash(path):
    result = hashlib.sha256()
    with Path(path).open("rb") as source:
        for chunk in iter(lambda: source.read(1024 * 1024), b""):
            result.update(chunk)
    return result.hexdigest()


def require(condition, message):
    if not condition:
        raise PairVerificationError(message)


def run(arguments):
    return subprocess.run(arguments, check=True, capture_output=True,
        text=True, timeout=30)


def signature(path, expected_team_id, runner=run):
    runner(["/usr/bin/codesign", "--verify", "--deep", "--strict", str(path)])
    display = runner(["/usr/bin/codesign", "--display", "--verbose=4", str(path)])
    output = display.stdout + display.stderr
    require("Signature=adhoc" not in output, "ad-hoc signature refused")
    authority = next((line.removeprefix("Authority=") for line in output.splitlines()
        if line.startswith("Authority=Developer ID Application:")), None)
    team = next((line.removeprefix("TeamIdentifier=") for line in output.splitlines()
        if line.startswith("TeamIdentifier=")), None)
    cdhash = next((line.removeprefix("CDHash=") for line in output.splitlines()
        if line.startswith("CDHash=")), None)
    require(authority is not None and team == expected_team_id,
        "Developer ID authority or expected team mismatch")
    require(cdhash is not None and re.fullmatch(r"[0-9a-f]{40,64}", cdhash),
        "missing code directory hash")
    requirement = runner(["/usr/bin/codesign", "--display", "--requirements", "-", str(path)])
    text = requirement.stdout + requirement.stderr
    designated = next((line.partition("designated => ")[2] for line in text.splitlines()
        if "designated => " in line), "")
    require(designated and not designated.startswith("cdhash "),
        "unstable designated requirement refused")
    return {"authority": authority, "teamID": team, "cdhash": cdhash,
        "designatedRequirement": designated, "strictVerified": True}


def bundle(path, expected_id, team, runner):
    path = Path(path).resolve(strict=True)
    info_path = path / "Contents/Info.plist"
    info = plistlib.loads(info_path.read_bytes())
    require(info["CFBundleIdentifier"] == expected_id, "bundle identity mismatch")
    executable = (path / "Contents/MacOS" / info["CFBundleExecutable"]).resolve(strict=True)
    require(executable.is_relative_to(path), "executable escapes its signed bundle")
    seal = path / "Contents/_CodeSignature/CodeResources"
    require(seal.is_file(), "signed resource seal missing")
    return info, {"appPath": str(path), "bundleID": expected_id,
        "executablePath": str(executable), "executableSHA256": file_hash(executable),
        "infoPlistSHA256": file_hash(info_path), "resourceSealSHA256": file_hash(seal),
        "signature": signature(path, team, runner)}


def generated_sdk_project(path, expected_sources):
    """Verify the compiler-input closure of Tuist's one SDK target.

    Raw generated bytes are separately sealed. This validates their input
    graph; it does not claim to reproduce Tuist or the compiler's machine code.
    """
    raw = path.read_bytes()
    require(len(raw) <= 2 * 1024 * 1024, "generated SDK project exceeds bound")
    try:
        graph = plistlib.loads(raw)
    except plistlib.InvalidFileException:
        result = subprocess.run(["/usr/bin/plutil", "-convert", "json", "-o", "-", str(path)],
            check=True, capture_output=True, timeout=30)
        require(len(result.stdout) <= 2 * 1024 * 1024, "generated SDK graph exceeds bound")
        graph = json.loads(result.stdout)
    require(isinstance(graph, dict) and isinstance(graph.get("objects"), dict),
        "invalid generated SDK graph")
    objects = graph["objects"]
    allowed_types = {"PBXBuildFile", "PBXFileReference", "PBXGroup", "PBXProject",
        "PBXNativeTarget", "PBXSourcesBuildPhase", "PBXFrameworksBuildPhase",
        "PBXResourcesBuildPhase", "PBXCopyFilesBuildPhase", "XCBuildConfiguration",
        "XCConfigurationList"}
    require(len(objects) <= 2048 and all(isinstance(item, dict)
        and item.get("isa") in allowed_types for item in objects.values()),
        "unknown generated SDK object, script or package")
    def object_with_type(identifier, kind):
        item = objects.get(identifier)
        require(isinstance(item, dict) and item.get("isa") == kind,
            "invalid generated SDK graph reference")
        return item
    project = object_with_type(graph.get("rootObject"), "PBXProject")
    require(sum(item["isa"] == "PBXProject" for item in objects.values()) == 1
        and project.get("projectDirPath", "") == "" and project.get("projectRoot", "") == ""
        and not project.get("packageReferences") and not project.get("projectReferences"),
        "generated SDK project escapes its source root")
    target_ids = project.get("targets", [])
    require(len(target_ids) == 1 and sum(item["isa"] == "PBXNativeTarget"
        for item in objects.values()) == 1, "generated SDK target closure differs")
    target = object_with_type(target_ids[0], "PBXNativeTarget")
    require(target.get("name") == target.get("productName") == "CmuxExtensionKit"
        and target.get("productType") == "com.apple.product-type.framework"
        and not target.get("dependencies") and not target.get("packageProductDependencies")
        and not target.get("buildRules"), "foreign generated SDK target input")
    phases = target.get("buildPhases", [])
    required_phases = {"PBXSourcesBuildPhase", "PBXFrameworksBuildPhase",
        "PBXResourcesBuildPhase", "PBXCopyFilesBuildPhase"}
    require(len(phases) == 4 and len(set(phases)) == 4
        and {objects.get(identifier, {}).get("isa") for identifier in phases} == required_phases
        and {identifier for identifier, item in objects.items()
            if item["isa"].endswith("BuildPhase")} == set(phases),
        "generated SDK build phase closure differs")
    source_builds = []
    for identifier in phases:
        phase = objects[identifier]
        files = phase.get("files", [])
        require(isinstance(files, list), "invalid SDK build files")
        if phase["isa"] == "PBXSourcesBuildPhase": source_builds = files
        else: require(files == [], "foreign generated SDK framework or resource")
    require(len(source_builds) == len(set(source_builds))
        and {identifier for identifier, item in objects.items() if item["isa"] == "PBXBuildFile"}
            == set(source_builds), "generated SDK compile files differ")
    source_refs = []
    for identifier in source_builds:
        build = object_with_type(identifier, "PBXBuildFile")
        require(set(build) == {"isa", "fileRef"}, "generated SDK per-file compiler flags refused")
        source_refs.append(build["fileRef"])
    require(len(source_refs) == len(set(source_refs)), "duplicate generated SDK compile input")
    resolved = {}
    visited = set()
    product_ref = target.get("productReference")
    def walk(identifier, parent):
        require(identifier not in visited, "generated SDK cyclic or multiply-parented input")
        visited.add(identifier)
        item = objects.get(identifier, {})
        require(item.get("isa") in {"PBXGroup", "PBXFileReference"}, "invalid SDK group child")
        if identifier == product_ref:
            require(item.get("isa") == "PBXFileReference"
                and item.get("sourceTree") == "BUILT_PRODUCTS_DIR"
                and item.get("path") == "CmuxExtensionKit.framework", "foreign generated SDK product")
            return
        require(item.get("sourceTree") == "<group>", "foreign generated SDK source tree")
        relative = item.get("path", "")
        require(isinstance(relative, str) and not Path(relative).is_absolute()
            and not any(part in {"..", "."} or "$" in part for part in Path(relative).parts),
            "generated SDK path escapes its input tree")
        current = parent / relative
        if item["isa"] == "PBXGroup":
            children = item.get("children", [])
            require(isinstance(children, list) and len(children) == len(set(children)), "invalid SDK children")
            for child in children: walk(child, current)
        else:
            require(relative and item.get("lastKnownFileType") in {"sourcecode.swift", "text.plist"},
                "foreign generated SDK file type")
            resolved[identifier] = str(current)
    walk(project.get("mainGroup"), Path())
    require(visited == {identifier for identifier, item in objects.items()
        if item["isa"] in {"PBXGroup", "PBXFileReference"}}, "orphan generated SDK input")
    actual_sources = [resolved.get(identifier) for identifier in source_refs]
    require(len(actual_sources) == len(expected_sources) and set(actual_sources) == expected_sources,
        "generated SDK sources differ from exact archived Swift inputs")
    require(all(objects[identifier].get("lastKnownFileType") == "sourcecode.swift"
        for identifier in source_refs), "generated SDK Swift input type differs")
    info_path = "Derived/InfoPlists/CmuxExtensionKit-Info.plist"
    require(set(resolved.values()) <= expected_sources | {info_path}, "foreign generated SDK file reference")
    # Close settings that can add compiler inputs, plugins, search roots or
    # alternate tools. Ordinary canonical warning/optimization settings are
    # bounded, included below, and sealed with the complete generated bytes.
    settings_keys = set("""ALWAYS_SEARCH_USER_PATHS CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED
        CLANG_ANALYZER_NONNULL CLANG_ANALYZER_NUMBER_OBJECT_CONVERSION CLANG_CXX_LANGUAGE_STANDARD
        CLANG_CXX_LIBRARY CLANG_ENABLE_MODULES CLANG_ENABLE_OBJC_ARC CLANG_ENABLE_OBJC_WEAK
        CLANG_WARN_BLOCK_CAPTURE_AUTORELEASING CLANG_WARN_BOOL_CONVERSION CLANG_WARN_COMMA
        CLANG_WARN_CONSTANT_CONVERSION CLANG_WARN_DEPRECATED_OBJC_IMPLEMENTATIONS
        CLANG_WARN_DIRECT_OBJC_ISA_USAGE CLANG_WARN_DOCUMENTATION_COMMENTS CLANG_WARN_EMPTY_BODY CLANG_WARN_ENUM_CONVERSION
        CLANG_WARN_INFINITE_RECURSION CLANG_WARN_INT_CONVERSION CLANG_WARN_NON_LITERAL_NULL_CONVERSION
        CLANG_WARN_OBJC_IMPLICIT_RETAIN_SELF CLANG_WARN_OBJC_LITERAL_CONVERSION CLANG_WARN_OBJC_ROOT_CLASS
        CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER CLANG_WARN_RANGE_LOOP_ANALYSIS
        CLANG_WARN_STRICT_PROTOTYPES CLANG_WARN_SUSPICIOUS_MOVE CLANG_WARN_UNGUARDED_AVAILABILITY
        CLANG_WARN_UNREACHABLE_CODE CLANG_WARN__DUPLICATE_METHOD_MATCH CODE_SIGN_IDENTITY
        COMBINE_HIDPI_IMAGES COPY_PHASE_STRIP CURRENT_PROJECT_VERSION DEAD_CODE_STRIPPING
        DEBUG_INFORMATION_FORMAT DEFINES_MODULE DYLIB_COMPATIBILITY_VERSION DYLIB_CURRENT_VERSION
        DYLIB_INSTALL_NAME_BASE ENABLE_NS_ASSERTIONS ENABLE_STRICT_OBJC_MSGSEND ENABLE_TESTABILITY
        FRAMEWORK_SEARCH_PATHS FRAMEWORK_VERSION GCC_C_LANGUAGE_STANDARD GCC_DYNAMIC_NO_PIC
        GCC_NO_COMMON_BLOCKS GCC_OPTIMIZATION_LEVEL GCC_PREPROCESSOR_DEFINITIONS
        GCC_WARN_64_TO_32_BIT_CONVERSION GCC_WARN_ABOUT_RETURN_TYPE GCC_WARN_INHIBIT_ALL_WARNINGS
        GCC_WARN_UNDECLARED_SELECTOR GCC_WARN_UNINITIALIZED_AUTOS GCC_WARN_UNUSED_FUNCTION
        GCC_WARN_UNUSED_VARIABLE INFOPLIST_FILE INSTALL_PATH LD_RUNPATH_SEARCH_PATHS MACH_O_TYPE
        MACOSX_DEPLOYMENT_TARGET MTL_ENABLE_DEBUG_INFO ONLY_ACTIVE_ARCH OTHER_SWIFT_FLAGS
        PRODUCT_BUNDLE_IDENTIFIER PRODUCT_NAME SDKROOT SKIP_INSTALL SWIFT_ACTIVE_COMPILATION_CONDITIONS
        SWIFT_COMPILATION_MODE SWIFT_OPTIMIZATION_LEVEL SWIFT_SUPPRESS_WARNINGS SWIFT_VERSION
        USE_HEADERMAP VALIDATE_PRODUCT VERSION_INFO_PREFIX VERSIONING_SYSTEM""".split())
    configuration_ids = set()
    configuration_lists = set()
    settings_proof = {}
    for owner, label in [(project, "project"), (target, "target")]:
        list_id = owner.get("buildConfigurationList")
        require(list_id not in configuration_lists, "shared SDK configuration list")
        configuration_lists.add(list_id)
        listing = object_with_type(list_id, "XCConfigurationList")
        configs = listing.get("buildConfigurations", [])
        require(len(configs) == 2 and {objects.get(identifier, {}).get("name")
            for identifier in configs} == {"Debug", "Release"}, "generated SDK configurations differ")
        for identifier in configs:
            require(identifier not in configuration_ids, "shared generated SDK configuration")
            configuration_ids.add(identifier)
            config = object_with_type(identifier, "XCBuildConfiguration")
            settings = config.get("buildSettings", {})
            require(not config.get("baseConfigurationReference") and isinstance(settings, dict)
                and set(settings) <= settings_keys, "foreign generated SDK compiler setting")
            require(all(isinstance(value, str) or (isinstance(value, list)
                and all(isinstance(part, str) for part in value)) for value in settings.values()),
                "invalid generated SDK compiler setting value")
            expected_flags = ["$(inherited)", "-package-name", "CmuxExtensionKit"] if label == "project" else "$(inherited)"
            require(settings.get("OTHER_SWIFT_FLAGS") == expected_flags,
                "foreign generated SDK compiler flags")
            closed_inputs = {"FRAMEWORK_SEARCH_PATHS": ["$(inherited)", "$(PLATFORM_DIR)/Developer/Library/Frameworks"],
                "LD_RUNPATH_SEARCH_PATHS": ["$(inherited)", "@executable_path/../Frameworks", "@loader_path/../Frameworks"],
                "SDKROOT": "macosx", "INFOPLIST_FILE": info_path, "MACH_O_TYPE": "staticlib",
                "PRODUCT_BUNDLE_IDENTIFIER": "CmuxExtensionKit", "DYLIB_INSTALL_NAME_BASE": "@rpath",
                "INSTALL_PATH": "$(LOCAL_LIBRARY_DIR)/Frameworks", "CODE_SIGN_IDENTITY": "",
                "SWIFT_VERSION": "5.0", "GCC_C_LANGUAGE_STANDARD": "gnu11"}
            require(all(key not in settings or settings[key] == expected
                for key, expected in closed_inputs.items()), "foreign generated SDK path or tool setting")
            # Xcode also compiles its automatic apple-generic version C source.
            # Its version/symbol inputs and the deployment target must not be
            # caller-controlled, including through project-level overrides.
            codegen = {"CURRENT_PROJECT_VERSION": "1", "VERSION_INFO_PREFIX": "",
                "VERSIONING_SYSTEM": "apple-generic", "FRAMEWORK_VERSION": "A",
                "DYLIB_COMPATIBILITY_VERSION": "1", "DYLIB_CURRENT_VERSION": "1",
                "MACOSX_DEPLOYMENT_TARGET": "14.0"}
            require(all((key in settings if label == "target" else True)
                and (key not in settings or settings[key] == expected)
                for key, expected in codegen.items()), "foreign or absent generated SDK codegen setting")
            if label == "target" and config["name"] == "Release":
                require("SWIFT_ACTIVE_COMPILATION_CONDITIONS" not in settings,
                    "foreign generated SDK Release compilation condition")
            else:
                conditions = ["$(inherited)", "SWIFT_PACKAGE"] if label == "project" else ["$(inherited)", "DEBUG"]
                require(settings.get("SWIFT_ACTIVE_COMPILATION_CONDITIONS") == conditions,
                    "foreign or absent generated SDK compilation condition")
            definitions = ["$(inherited)"] + (["DEBUG=1"] if config["name"] == "Debug" else []) + ["SWIFT_PACKAGE=1"]
            require("GCC_PREPROCESSOR_DEFINITIONS" not in settings
                or label == "project" and settings["GCC_PREPROCESSOR_DEFINITIONS"] == definitions,
                "foreign generated SDK preprocessor input")
            mode = "singlefile" if config["name"] == "Debug" else "wholemodule"
            optimization = "-Onone" if config["name"] == "Debug" else "-O"
            require(("SWIFT_COMPILATION_MODE" in settings if label == "target" else True)
                and ("SWIFT_COMPILATION_MODE" not in settings or settings["SWIFT_COMPILATION_MODE"] == mode),
                "foreign generated SDK compilation mode")
            require(("SWIFT_OPTIMIZATION_LEVEL" in settings if label == "target" else True)
                and ("SWIFT_OPTIMIZATION_LEVEL" not in settings or settings["SWIFT_OPTIMIZATION_LEVEL"] == optimization),
                "foreign generated SDK optimization flag")
            if label == "target":
                require(settings.get("INFOPLIST_FILE") == info_path
                    and settings.get("MACH_O_TYPE") == "staticlib"
                    and settings.get("PRODUCT_NAME") == "CmuxExtensionKit", "generated SDK target settings differ")
            else: require(settings.get("PRODUCT_NAME", "$(TARGET_NAME)") == "$(TARGET_NAME)", "SDK project product differs")
            settings_proof[label + ":" + config["name"]] = settings
    require(configuration_ids == {identifier for identifier, item in objects.items()
        if item["isa"] == "XCBuildConfiguration"}, "orphan generated SDK compiler configuration")
    require(configuration_lists == {identifier for identifier, item in objects.items()
        if item["isa"] == "XCConfigurationList"}, "orphan SDK configuration list")
    # This closes the archived Swift source graph and known automatic version
    # generation settings. It does not claim that Swift files are every input
    # the Xcode toolchain generates or independently reproduce compiled bytes.
    return fingerprint({"sourcePaths": sorted(expected_sources), "settings": settings_proof})


def sdk_proof(source, revision, materialized):
    require(re.fullmatch(r"[0-9a-f]{40}", revision), "SDK revision must be exact")
    prefix = "Packages/macOS/CmuxExtensionKit"
    result = subprocess.run(["/usr/bin/git", "-C", str(source), "archive",
        revision, prefix], check=True, capture_output=True, timeout=30)
    require(len(result.stdout) <= 8 * 1024 * 1024, "SDK archive exceeds bound")
    expected = {}
    with tarfile.open(fileobj=io.BytesIO(result.stdout)) as archive:
        for member in archive:
            if member.isdir():
                continue
            require(member.isfile(), "SDK archive contains a link or special file")
            relative = Path(member.name).relative_to(prefix)
            expected[str(relative)] = hashlib.sha256(archive.extractfile(member).read()).hexdigest()
    materialized = Path(materialized)
    require(not materialized.is_symlink(), "materialized SDK root contains a symlink")
    require((materialized / ".source-revision").read_text().strip() == revision,
        "compiled SDK pin marker mismatch")
    actual = {}
    for path in materialized.rglob("*"):
        relative = path.relative_to(materialized)
        require(not path.is_symlink(), "materialized SDK contains a symlink")
        if relative.parts[0] in {".build", ".git"} or str(relative) in {".source-revision", "VENDORED.md"}:
            continue
        if path.is_file():
            require(path.stat().st_size <= 2 * 1024 * 1024, "materialized SDK file exceeds bound")
            actual[str(relative)] = file_hash(path)
    require({key: actual.get(key) for key in expected} == expected,
        "compiled SDK differs from its exact source object")
    generated = {key: value for key, value in actual.items() if key not in expected}
    project_prefix = "CmuxExtensionKit.xcodeproj/"
    generated_paths = {project_prefix + "project.pbxproj",
        project_prefix + "project.xcworkspace/contents.xcworkspacedata",
        project_prefix + "xcuserdata/" + pwd.getpwuid(os.getuid()).pw_name + ".xcuserdatad/xcschemes/xcschememanagement.plist",
        "Derived/InfoPlists/CmuxExtensionKit-Info.plist"}
    require(not generated or set(generated) == generated_paths, "unknown generated SDK artifact")
    source_paths = {key for key in expected if key.startswith("Sources/CmuxExtensionKit/") and key.endswith(".swift")}
    require(source_paths, "archived SDK has no Swift compile inputs")
    closure = None
    if generated:
        closure = generated_sdk_project(materialized / (project_prefix + "project.pbxproj"), source_paths)
        workspace = ET.fromstring((materialized / (project_prefix + "project.xcworkspace/contents.xcworkspacedata")).read_bytes())
        require(workspace.tag == "Workspace" and workspace.attrib == {"version": "1.0"}
            and len(workspace) == 1 and workspace[0].tag == "FileRef"
            and workspace[0].attrib == {"location": "self:"} and len(workspace[0]) == 0,
            "foreign generated SDK workspace")
        scheme = next(key for key in generated_paths if key.endswith("xcschememanagement.plist"))
        require(plistlib.loads((materialized / scheme).read_bytes()) == {"SchemeUserState": {}},
            "foreign generated SDK scheme")
        info = plistlib.loads((materialized / "Derived/InfoPlists/CmuxExtensionKit-Info.plist").read_bytes())
        require(info == {"CFBundleDevelopmentRegion": "$(DEVELOPMENT_LANGUAGE)",
            "CFBundleExecutable": "$(EXECUTABLE_NAME)", "CFBundleIdentifier": "$(PRODUCT_BUNDLE_IDENTIFIER)",
            "CFBundleInfoDictionaryVersion": "6.0", "CFBundleName": "$(PRODUCT_NAME)",
            "CFBundlePackageType": "FMWK", "CFBundleShortVersionString": "1.0", "CFBundleVersion": "1",
            "NSHumanReadableCopyright": "Copyright ©. All rights reserved."}, "foreign generated SDK Info.plist")
    tree = subprocess.run(["/usr/bin/git", "-C", str(source), "rev-parse",
        revision + ":" + prefix], check=True, capture_output=True, text=True,
        timeout=30).stdout.strip()
    return {"revision": revision, "source": str(Path(source).resolve(strict=True)),
        # sourcePaths enumerates archived Swift files, not automatic Xcode C.
        "treeSHA": tree, "filesFingerprint": fingerprint(expected), "sourcePaths": sorted(source_paths),
        "generatedArtifacts": generated, "generatedArtifactsFingerprint": fingerprint(generated),
        "generatedCompilerClosureFingerprint": closure}


def requested_manifest(source_path, revision, extension_info):
    """Read only the exact built source object; no model-supplied scope list."""
    text = run(["/usr/bin/git", "-C", str(source_path), "show", revision +
        ":Sources/CortexSessionsExtension/CortexSessionsExtension.swift"]).stdout
    def scopes(name):
        match = re.search(name + r":\s*\[([^]]+)\]", text)
        require(match is not None, "built extension scope declaration missing")
        values = re.findall(r"\.([A-Za-z][A-Za-z0-9]*)", match.group(1))
        require(values and len(values) <= 64 and len(values) == len(set(values)),
            "built extension scope declaration invalid")
        return sorted(values)
    require("minimumAPIVersion: .sidebarV2_3" in text,
        "built extension does not declare the required API 2.3")
    identifier = extension_info.get("CortexSessionsExtensionIdentifier")
    require(isinstance(identifier, str) and identifier, "signed manifest identity missing")
    return {"id": identifier, "apiVersion": {"major": 2, "minor": 3},
        "readScopes": scopes("readScopes"), "actionScopes": scopes("actionScopes"),
        "sourcePath": "Sources/CortexSessionsExtension/CortexSessionsExtension.swift",
        "sourceSHA256": hashlib.sha256(text.encode()).hexdigest()}


def attest(pair_path, host_path, source_path, expected_team_id="YZYJJPX484", runner=run):
    pair = json.loads(Path(pair_path).read_text())
    host_receipt = json.loads(Path(host_path).read_text())
    sources = json.loads(Path(source_path).read_text())
    tag = pair["tag"]
    require(re.fullmatch(r"[a-z0-9][a-z0-9-]{0,31}", tag), "invalid dogfood tag")
    require(pair["mainLaunchAllowed"] is False and pair["productionInstallAllowed"] is False
        and pair["hostFallbackAllowed"] is False, "production activation or fallback refused")
    require(sources["productionActivationAllowed"] is False
        and sources["sourceArchivesIncludeForeignWIP"] is False, "source isolation proof missing")
    require(pair["mainBundleID"] == "fr.yoyaku.cortex.dogfood." + tag,
        "Cortex tag identity mismatch")
    expected_host_id = "com.cmuxterm.app.debug." + tag.replace("-", ".")
    require(host_receipt["bundleID"] == expected_host_id, "CMUX tag identity mismatch")
    require(pair["extensionPoint"] == expected_host_id + ".cmux.sidebar",
        "paired extension point mismatch")
    require(pair["extensionBundleID"] == pair["mainBundleID"] + ".sessions",
        "extension parent identity mismatch")
    require(str(pair["cortexGitDirty"]).lower() == "false", "dirty Cortex build refused")
    require(pair["cortexGitSHA"] == sources["CortexArtifactSHA"]
        and host_receipt["hostGitSHA"] == sources["cmuxArtifactSHA"],
        "built source heads differ from immutable source receipt")
    host_info, host = bundle(host_receipt["appPath"], expected_host_id, expected_team_id, runner)
    cortex_info, cortex = bundle(pair["appPath"], pair["mainBundleID"], expected_team_id, runner)
    extension_info, extension = bundle(pair["extensionPath"], pair["extensionBundleID"], expected_team_id, runner)
    require(Path(extension["appPath"]).is_relative_to(Path(cortex["appPath"])),
        "extension escapes its signed parent")
    require(cortex_info.get("CortexDogfoodMainLaunchDisabled") is True,
        "tagged main launch guard missing")
    require(cortex_info.get("CortexGitSHA") == pair["cortexGitSHA"]
        and str(cortex_info.get("CortexGitDirty")).lower() == "false",
        "signed Cortex provenance mismatch")
    require(cortex_info.get("CortexPairedSDKRevision") == pair["sdkRevision"],
        "signed Cortex SDK revision mismatch")
    require(extension_info["EXAppExtensionAttributes"]["EXExtensionPointIdentifier"]
        == pair["extensionPoint"], "signed extension point mismatch")
    env = host_info.get("LSEnvironment", {})
    host_root = Path(host["appPath"])
    cli = host_root / "Contents/Resources/bin/cmux"
    shells = host_root / "Contents/Resources/shell-integration"
    require(cli.is_file() and shells.is_dir(), "bundled execution resources missing")
    require(Path(env.get("CMUX_BUNDLED_CLI_PATH", "")).resolve() == cli.resolve()
        and Path(env.get("CMUX_SHELL_INTEGRATION_DIR", "")).resolve() == shells.resolve(),
        "bundled execution paths are stale or escape the current host")
    require(Path(host_receipt["cliPath"]).resolve() == cli.resolve()
        and host_receipt["cliSHA256"] == file_hash(cli), "bundled CLI receipt mismatch")
    socket = "/tmp/cmux-debug-" + tag + ".sock"
    require(env.get("CMUX_SOCKET_PATH") == socket and env.get("CMUX_TAG") == tag
        and env.get("CMUX_BUNDLE_ID") == expected_host_id, "host socket isolation mismatch")
    sdk = sdk_proof(pair["sdkSource"], pair["sdkRevision"],
        Path(source_path).parent / "Cortex/Vendor/cmux-extension-kit")
    # The host and compiled extension must use the same interface tree.
    host_sdk_tree = subprocess.run(["/usr/bin/git", "-C", pair["sdkSource"],
        "rev-parse", sources["cmuxArtifactSHA"] + ":Packages/macOS/CmuxExtensionKit"],
        check=True, capture_output=True, text=True, timeout=30).stdout.strip()
    require(host_sdk_tree == sdk["treeSHA"], "host and extension SDK interface trees differ")
    execution = {"cliPath": str(cli.resolve()), "cliSHA256": file_hash(cli),
        "shellIntegrationPath": str(shells.resolve()), "socketPath": socket,
        "hostAppPath": host["appPath"], "cortexAppPath": cortex["appPath"],
        "extensionPath": extension["appPath"], "sdkSource": sdk["source"],
        "cmuxAPIMinimum": pair["cmuxAPIMinimum"]}
    sealed = {"tag": tag, "extensionPoint": pair["extensionPoint"],
        "host": host, "cortex": cortex, "extension": extension, "sdk": sdk,
        "cmuxGitSHA": sources["cmuxArtifactSHA"], "cortexGitSHA": sources["CortexArtifactSHA"],
        "sourceReceiptSHA256": file_hash(source_path),
        "extensionManifest": requested_manifest(Path(source_path).parent / "Cortex",
            sources["CortexArtifactSHA"], extension_info)}
    return {"schemaVersion": 1, "verificationState": "sealed",
        "verified_pair_fingerprint": fingerprint(sealed),
        "executable_config_fingerprint": fingerprint(execution),
        "pair": sealed, "execution": execution, "runtimeVerified": False,
        "productionInstallAllowed": False, "mainLaunchAllowed": False,
        "producerSHA256": file_hash(__file__),
        "buildInputs": {"pairConfig": str(Path(pair_path).resolve(strict=True)),
            "hostReceipt": str(Path(host_path).resolve(strict=True)),
            "sourceReceipt": str(Path(source_path).resolve(strict=True)),
            "expectedTeamID": expected_team_id}}


def revalidate(manifest_path, runner=run):
    """Recheck actual files and signatures; never trust a model-made receipt."""
    previous = json.loads(Path(manifest_path).read_text())
    require(previous.get("verificationState") == "sealed"
        and previous.get("runtimeVerified") is False, "unsupported readiness claim")
    inputs = previous["buildInputs"]
    actual = attest(inputs["pairConfig"], inputs["hostReceipt"],
        inputs["sourceReceipt"], inputs["expectedTeamID"], runner)
    require(actual == previous, "pair changed after immutable attestation")
    return actual


def process_executable(pid):
    require(type(pid) is int and pid > 0, "invalid native process ID")
    library = ctypes.CDLL("/usr/lib/libproc.dylib")
    path = ctypes.create_string_buffer(4096)
    count = library.proc_pidpath(pid, path, len(path))
    require(count > 0, "native process disappeared")
    return str(Path(path.value.decode()).resolve(strict=True))


def process_identity(pid):
    executable = process_executable(pid)
    started = run(["/bin/ps", "-p", str(pid), "-o", "lstart="]).stdout.strip()
    require(started, "native process start identity missing")
    return {"pid": pid, "executablePath": executable,
        "startedAt": started}


def extension_processes(executable):
    # Iterate process IDs, then resolve kernel executable paths. Never match a
    # command-line substring containing a model or conversation argument.
    pids = run(["/bin/ps", "-axo", "pid="]).stdout.split()
    found = []
    for value in pids:
        try:
            pid = int(value)
            if process_executable(pid) != executable:
                continue
            identity = process_identity(pid)
        except (PairVerificationError, FileNotFoundError, subprocess.CalledProcessError):
            continue
        if identity["executablePath"] == executable:
            found.append(identity)
    require(0 < len(found) <= 16, "paired extension process is not running")
    return sorted(found, key=lambda item: item["pid"])


def require_socket(path):
    require(stat.S_ISSOCK(Path(path).stat().st_mode), "isolated native socket is not present")


def observe_runtime(sealed, runner=run, process_reader=process_identity,
                    process_finder=extension_processes):
    """Verify existing native status, exact socket and actual process identities.

    Old hosts without effective grant telemetry remain fail closed. Configured
    preferences are deliberately separate from in-memory, generation-bound grants.
    """
    execution, pair = sealed["execution"], sealed["pair"]
    socket = execution["socketPath"]
    require_socket(socket)
    def rpc(method):
        output = runner([execution["cliPath"], "--socket", socket, "--json", "rpc", method, "{}"]).stdout
        require(len(output.encode()) <= 256 * 1024, "runtime metadata exceeds bound")
        value = json.loads(output)
        if "result" in value:
            require(value.get("ok") is not False, "native RPC failed")
            value = value["result"]
        require(isinstance(value, dict), "native metadata result is not an object")
        return value
    identify = rpc("system.identify")
    for key, expected in {"app_bundle_path": pair["host"]["appPath"],
        "app_executable_path": pair["host"]["executablePath"],
        "app_cli_path": execution["cliPath"], "bundle_identifier": pair["host"]["bundleID"],
        "socket_path": socket}.items():
        require(identify.get(key) == expected, "live host identity mismatch: " + key)
    capabilities = rpc("system.capabilities")
    require(capabilities.get("socket_path") == socket, "capability socket mismatch")
    methods = capabilities.get("methods", [])
    required = {"system.identify", "system.capabilities", "extension.sidebar.status",
        "extension.sidebar.snapshot", "workspace.context.export", "workspace.context.import"}
    require(required.issubset(set(methods)), "native contract methods missing")
    status = rpc("extension.sidebar.status")
    require(status.get("provider_id") == "cmux.sidebar.extensions"
        and status.get("provider_active") is True and status.get("connected") is True
        and status.get("selected_bundle_id") == pair["extension"]["bundleID"],
        "paired extension is not selected and snapshot-acknowledged")
    hosts = status.get("hosts")
    require(isinstance(hosts, list) and 0 < len(hosts) <= 16, "live host inventory invalid")
    manifest = pair["extensionManifest"]
    telemetry = []
    for host in hosts:
        require(host.get("bundle_id") == pair["extension"]["bundleID"]
            and host.get("state") == "connected", "selected host is not connected")
        fields = {"manifest_id", "api_version", "connection_generation", "grant_revision",
            "effective_read_scopes", "effective_action_scopes"}
        require(fields.issubset(host), "runtime_grants_not_observable")
        require(host["manifest_id"] == manifest["id"]
            and host["api_version"] == manifest["apiVersion"], "runtime manifest/API mismatch")
        for field in ["generation", "connection_generation", "grant_revision"]:
            require(type(host.get(field)) is int and host[field] >= 0, "invalid runtime generation fence")
        require(sorted(host["effective_read_scopes"]) == manifest["readScopes"]
            and sorted(host["effective_action_scopes"]) == manifest["actionScopes"],
            "runtime effective grant is incomplete or differs from built manifest")
        native = process_reader(host.get("pid"))
        require(native["executablePath"] == pair["host"]["executablePath"],
            "connected host process is not the sealed executable")
        native_signature = signature(str(native["pid"]), pair["host"]["signature"]["teamID"], runner)
        require(native_signature == pair["host"]["signature"], "running host signature differs from sealed pair")
        native["signature"] = native_signature
        telemetry.append({key: host[key] for key in ["host_id", "bundle_id", "identity_id", "generation",
            "manifest_id", "api_version", "connection_generation", "grant_revision",
            "effective_read_scopes", "effective_action_scopes"]} | {"process": native})
    host_pids = {row["process"]["pid"] for row in telemetry}
    require(len(host_pids) == 1, "multiple native host processes refused")
    pid = next(iter(host_pids))
    sockets = runner(["/usr/sbin/lsof", "-a", "-p", str(pid), "-U", "-Fn"]).stdout.splitlines()
    require("n" + socket in sockets, "selected process does not own the isolated socket")
    extensions = process_finder(pair["extension"]["executablePath"])
    require(all(item["executablePath"] == pair["extension"]["executablePath"] for item in extensions)
        and 0 < len(extensions) <= 16, "paired extension executable is not running")
    for extension in extensions:
        native_signature = signature(str(extension["pid"]), pair["extension"]["signature"]["teamID"], runner)
        require(native_signature == pair["extension"]["signature"], "running extension signature differs from sealed pair")
        extension["signature"] = native_signature
    configured_data = runner(["/usr/bin/defaults", "export", pair["host"]["bundleID"], "-"]).stdout
    require(len(configured_data.encode()) <= 1024 * 1024, "configured preferences exceed bound")
    preferences = plistlib.loads(configured_data.encode())
    raw = preferences.get("cmuxExtensionSidebar.grants.v1")
    require(isinstance(raw, bytes), "configured grant record missing")
    configured = json.loads(raw).get(pair["extension"]["bundleID"])
    require(isinstance(configured, dict), "configured paired grant record missing")
    require(configured.get("manifestID") == manifest["id"]
        and configured.get("apiVersion") == manifest["apiVersion"], "configured manifest identity mismatch")
    configured = {key: configured[key] for key in ["manifestID", "apiVersion", "readScopes", "actionScopes"]}
    # Read status again after filesystem/process checks. Any reconnect, revoke,
    # revision change or replacement invalidates this sample rather than racing readiness.
    after = rpc("extension.sidebar.status")
    require(after == status, "native connection or grant changed during runtime verification")
    runtime = {"socketPath": socket, "hostProcess": telemetry[0]["process"],
        "extensionProcesses": extensions, "hosts": sorted(telemetry, key=lambda item: item["host_id"]),
        "configuredGrant": configured, "configuredGrantFingerprint": fingerprint(configured),
        "effectiveGrantSource": "native-host-memory-at-connection-generation",
        "apiVersion": manifest["apiVersion"], "nativeMethods": sorted(required),
        "socketProtocolVersion": capabilities.get("version")}
    return runtime


def attest_live(sealed_path, runner=run, process_reader=process_identity,
                process_finder=extension_processes):
    sealed = revalidate(sealed_path, runner)
    runtime = observe_runtime(sealed, runner, process_reader, process_finder)
    return {"schemaVersion": 1, "verificationState": "live", "runtimeVerified": True,
        "verified_pair_fingerprint": sealed["verified_pair_fingerprint"],
        "executable_config_fingerprint": sealed["executable_config_fingerprint"],
        "runtime_fingerprint": fingerprint(runtime), "runtime": runtime,
        "observedAt": datetime.now(timezone.utc).isoformat(),
        "sealedManifest": str(Path(sealed_path).resolve(strict=True)),
        "producerSHA256": file_hash(__file__), "productionInstallAllowed": False,
        "mainLaunchAllowed": False}


def revalidate_live(manifest_path, runner=run, process_reader=process_identity,
                    process_finder=extension_processes):
    previous = json.loads(Path(manifest_path).read_text())
    require(previous.get("verificationState") == "live" and previous.get("runtimeVerified") is True,
        "live verification receipt missing")
    actual = attest_live(previous["sealedManifest"], runner, process_reader, process_finder)
    for key in ["schemaVersion", "verificationState", "runtimeVerified", "verified_pair_fingerprint",
        "executable_config_fingerprint", "runtime_fingerprint", "producerSHA256",
        "productionInstallAllowed", "mainLaunchAllowed"]:
        require(actual[key] == previous.get(key), "live pair identity changed: " + key)
    return actual


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--pair-config", type=Path)
    parser.add_argument("--host-receipt", type=Path)
    parser.add_argument("--source-receipt", type=Path)
    parser.add_argument("--expected-team-id", default="YZYJJPX484")
    parser.add_argument("--output", type=Path)
    parser.add_argument("--validate", type=Path)
    parser.add_argument("--live", type=Path, help="Existing sealed manifest to verify against actual runtime")
    parser.add_argument("--validate-live", type=Path)
    args = parser.parse_args()
    modes = [args.validate, args.live, args.validate_live]
    require(sum(bool(mode) for mode in modes) <= 1, "choose one verification mode")
    if args.validate or args.validate_live:
        require(not any([args.pair_config, args.host_receipt, args.source_receipt, args.output]),
            "validation cannot replace build inputs")
        result = revalidate_live(args.validate_live) if args.validate_live else revalidate(args.validate)
    elif args.live:
        require(args.output and not any([args.pair_config, args.host_receipt, args.source_receipt]),
            "live verification requires a sealed manifest and new output")
        result = attest_live(args.live)
    else:
        require(all([args.pair_config, args.host_receipt, args.source_receipt, args.output]),
            "all canonical build receipts and a new output are required")
        result = attest(args.pair_config, args.host_receipt, args.source_receipt, args.expected_team_id)
    if args.output:
        require(not args.output.exists(), "immutable attestation output already exists")
        descriptor = os.open(args.output, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
        with os.fdopen(descriptor, "w") as destination:
            destination.write(json.dumps(result, sort_keys=True, indent=2) + "\n")
    print(json.dumps({key: result[key] for key in ("schemaVersion", "verificationState",
        "verified_pair_fingerprint", "executable_config_fingerprint", "runtimeVerified")}))


if __name__ == "__main__":
    main()
